#!/bin/bash
HOST=$(cat server/config/local.py | grep -F "config['host']" | head -n 1 | perl -pe "s/.+'(.+)'.*/\1/")
while true
do
    STATS=$(./stats.py $HOST "$@")
    clear
    echo $"$STATS"
    sleep 1
done
